#!/bin/bash

echo "Testing agent output format from frontend..."
echo ""
echo "Open this URL in your browser:"
echo "http://txt2sql-frontend-194561596031.s3-website.eu-central-1.amazonaws.com"
echo ""
echo "Then try these queries:"
echo ""
echo "1. Show me 5 incidents with code E_A_C_09"
echo "   → Should return ONLY key columns (incident_code, incident_description, uti_2_1, valuation_amount, etc.)"
echo "   → NOT all 200+ columns"
echo ""
echo "2. Show me 10 records from test_population"
echo "   → Should select specific columns"
echo ""
echo "3. How many incidents have code E_A_C_09?"
echo "   → Should show count"
echo ""
echo "Expected improvement:"
echo "Before: Long CSV string with 200+ columns"
echo "After:  Clean table with 5-10 relevant columns only"
echo ""
echo "If you still see all 200+ columns, the agent instruction needs more time to propagate."
echo "Wait another minute and try again."
