AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 with ALB for Streamlit - Simple and Reliable'

Parameters:
  Alias:
    Type: String
    Default: txt2sql-dev
    Description: Environment alias
  
  AgentId:
    Type: String
    Description: Bedrock Agent ID
    NoEcho: false
  
  AgentAliasId:
    Type: String
    Description: Bedrock Agent Alias ID
    NoEcho: false
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID
  
  SubnetIds:
    Type: CommaDelimitedList
    Description: Comma-separated list of subnet IDs (at least 2 for ALB)
  
  InstanceType:
    Type: String
    Default: t3.small
    AllowedValues:
      - t3.small
      - t3.medium
      - t3.large

Resources:
  # Security Group for ALB
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${Alias}-alb-sg'
  
  # Security Group for EC2
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2 Streamlit app
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8501
          ToPort: 8501
          SourceSecurityGroupId: !Ref ALBSecurityGroup
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${Alias}-ec2-sg'
  
  # IAM Role for EC2
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
  
  # Instance Profile
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role
  
  # Application Load Balancer
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${Alias}-streamlit-alb'
      Type: application
      Scheme: internet-facing
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Subnets: !Ref SubnetIds
      Tags:
        - Key: Name
          Value: !Sub '${Alias}-streamlit-alb'
  
  # Target Group
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${Alias}-streamlit-tg'
      Port: 8501
      Protocol: HTTP
      VpcId: !Ref VpcId
      HealthCheckPath: /_stcore/health
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      TargetType: instance
      Matcher:
        HttpCode: '200'
  
  # ALB Listener
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
  
  # EC2 Instance
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Sub "{{resolve:ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id}}"
      IamInstanceProfile: !Ref InstanceProfile
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      SubnetId: !Select [0, !Ref SubnetIds]
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
          
          TARGET_GROUP_ARN="${TargetGroup}"
          
          # Update system
          apt-get update -y
          apt-get upgrade -y
          apt-get install -y python3-pip git curl
          
          # Install Streamlit and dependencies
          pip3 install streamlit boto3 requests pandas pillow
          
          # Create app directory
          mkdir -p /home/ubuntu/app/streamlit_app
          cd /home/ubuntu/app/streamlit_app
          
          # Download app files (you'll need to upload these or clone from your repo)
          # For now, create a minimal working version
          cat > app.py << 'APPEOF'
          import streamlit as st
          import os
          import boto3
          from invoke_agent import invoke_agent
          
          st.set_page_config(page_title="Text2SQL Agent", layout="wide")
          st.title("Text2SQL Agent - Amazon Athena")
          
          prompt = st.text_input("Please enter your query?", max_chars=2000)
          submit_button = st.button("Submit", type="primary")
          
          if submit_button and prompt:
              with st.spinner("Processing..."):
                  try:
                      response = invoke_agent(prompt)
                      st.success("Query executed successfully!")
                      st.json(response)
                  except Exception as e:
                      st.error(f"Error: {str(e)}")
          APPEOF
          
          # Download invoke_agent.py (simplified version)
          cat > invoke_agent.py << 'INVOKEEOF'
          import os
          import boto3
          import json
          
          def invoke_agent(prompt):
              bedrock_agent = boto3.client('bedrock-agent-runtime', region_name=os.environ.get('AWS_REGION', 'eu-central-1'))
              agent_id = os.environ.get('AGENT_ID')
              alias_id = os.environ.get('AGENT_ALIAS_ID')
              
              response = bedrock_agent.invoke_agent(
                  agentId=agent_id,
                  agentAliasId=alias_id,
                  sessionId='default',
                  inputText=prompt
              )
              
              result = ""
              for event in response['completion']:
                  if 'chunk' in event:
                      result += event['chunk']['bytes'].decode('utf-8')
              
              return json.loads(result) if result else {"message": "No response"}
          INVOKEEOF
          
          # Create systemd service
          cat > /etc/systemd/system/streamlit-txt2sql.service << 'EOF'
          [Unit]
          Description=Streamlit Text2SQL Agent App
          After=network.target
          
          [Service]
          Type=simple
          User=ubuntu
          WorkingDirectory=/home/ubuntu/app/streamlit_app
          Environment="PATH=/usr/local/bin:/usr/bin:/bin"
          Environment="AWS_REGION=${AWS::Region}"
          Environment="AGENT_ID=${AgentId}"
          Environment="AGENT_ALIAS_ID=${AgentAliasId}"
          ExecStart=/usr/local/bin/streamlit run app.py --server.port=8501 --server.address=0.0.0.0 --server.headless=true
          Restart=always
          RestartSec=10
          
          [Install]
          WantedBy=multi-user.target
          EOF
          
          # Enable and start service
          systemctl daemon-reload
          systemctl enable streamlit-txt2sql
          
          # Wait a bit then start
          sleep 10
          systemctl start streamlit-txt2sql
          
          # Register instance with target group
          INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
          sleep 60  # Wait for ALB and target group to be ready
          for i in {1..5}; do
            aws elbv2 register-targets \
              --target-group-arn "$TARGET_GROUP_ARN" \
              --targets Id=$INSTANCE_ID,Port=8501 \
              --region ${AWS::Region} && echo "Target registered successfully" && break || sleep 10
          done
      Tags:
        - Key: Name
          Value: !Sub '${Alias}-streamlit-ec2'

Outputs:
  LoadBalancerDNS:
    Description: DNS name of the Application Load Balancer
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub '${Alias}-StreamlitALBDNS'
  
  LoadBalancerURL:
    Description: Full URL to access the Streamlit app
    Value: !Sub 'http://${ApplicationLoadBalancer.DNSName}'
    Export:
      Name: !Sub '${Alias}-StreamlitURL'
  
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance

